import { MiddlewareRoute } from "@medusajs/framework"
import { validateAndTransformBody } from "@medusajs/framework/http"
import {
  CreateComponentSchema,
  AddComponentToPackSchema,
  ApplyPackApplicabilitySchema,
  BulkAddComponentsToPackSchema,
  CreateComponentPackSchema,
  DetachPackApplicabilitySchema,
  CreateHelpAnnotationSchema,
  CreateRuleFromPresetSchema,
  CreateRulePresetSchema,
  CreateRuleSchema,
  CreateServerModelSchema,
  EnableRuleWithConfirmationSchema,
  PreviewPackApplicabilitySchema,
  ReorderPackItemsSchema,
  ReviewRuleSchema,
  SimulateConfigurationSchema,
  UpdateComponentApplicabilitySchema,
  UpdateComponentPackSchema,
  UpdateComponentSchema,
  UpdateHelpAnnotationSchema,
  UpdateRulePresetSchema,
  UpdateRuleSchema,
  UpdateServerModelSchema,
} from "./validators"

export const serverConfiguratorAdminMiddlewares: MiddlewareRoute[] = [
  { matcher: "/admin/server-configurator/models", method: "POST", middlewares: [validateAndTransformBody(CreateServerModelSchema)] },
  { matcher: "/admin/server-configurator/models/:id", method: "POST", middlewares: [validateAndTransformBody(UpdateServerModelSchema)] },
  { matcher: "/admin/server-configurator/components", method: "POST", middlewares: [validateAndTransformBody(CreateComponentSchema)] },
  { matcher: "/admin/server-configurator/components/:id", method: "POST", middlewares: [validateAndTransformBody(UpdateComponentSchema)] },
  { matcher: "/admin/server-configurator/components/:id/applicability", method: "POST", middlewares: [validateAndTransformBody(UpdateComponentApplicabilitySchema)] },
  { matcher: "/admin/server-configurator/component-packs", method: "POST", middlewares: [validateAndTransformBody(CreateComponentPackSchema)] },
  { matcher: "/admin/server-configurator/component-packs/:id", method: "POST", middlewares: [validateAndTransformBody(UpdateComponentPackSchema)] },
  { matcher: "/admin/server-configurator/component-packs/:id/items", method: "POST", middlewares: [validateAndTransformBody(AddComponentToPackSchema)] },
  { matcher: "/admin/server-configurator/component-packs/:id/items/reorder", method: "POST", middlewares: [validateAndTransformBody(ReorderPackItemsSchema)] },
  { matcher: "/admin/server-configurator/component-packs/:id/bulk-add-components", method: "POST", middlewares: [validateAndTransformBody(BulkAddComponentsToPackSchema)] },
  { matcher: "/admin/server-configurator/component-packs/:id/preview-applicability", method: "POST", middlewares: [validateAndTransformBody(PreviewPackApplicabilitySchema)] },
  { matcher: "/admin/server-configurator/component-packs/:id/apply-applicability", method: "POST", middlewares: [validateAndTransformBody(ApplyPackApplicabilitySchema)] },
  { matcher: "/admin/server-configurator/component-packs/:id/detach-applicability", method: "POST", middlewares: [validateAndTransformBody(DetachPackApplicabilitySchema)] },
  { matcher: "/admin/server-configurator/rules", method: "POST", middlewares: [validateAndTransformBody(CreateRuleSchema)] },
  { matcher: "/admin/server-configurator/rules/:id", method: "POST", middlewares: [validateAndTransformBody(UpdateRuleSchema)] },
  { matcher: "/admin/server-configurator/rules/:id/review", method: "POST", middlewares: [validateAndTransformBody(ReviewRuleSchema)] },
  { matcher: "/admin/server-configurator/rules/:id/enable-with-confirmation", method: "POST", middlewares: [validateAndTransformBody(EnableRuleWithConfirmationSchema)] },
  { matcher: "/admin/server-configurator/rule-presets", method: "POST", middlewares: [validateAndTransformBody(CreateRulePresetSchema)] },
  { matcher: "/admin/server-configurator/rule-presets/:id", method: "POST", middlewares: [validateAndTransformBody(UpdateRulePresetSchema)] },
  { matcher: "/admin/server-configurator/rule-presets/:id/create-rule", method: "POST", middlewares: [validateAndTransformBody(CreateRuleFromPresetSchema)] },
  { matcher: "/admin/server-configurator/help-annotations", method: "POST", middlewares: [validateAndTransformBody(CreateHelpAnnotationSchema)] },
  { matcher: "/admin/server-configurator/help-annotations/:id", method: "POST", middlewares: [validateAndTransformBody(UpdateHelpAnnotationSchema)] },
  { matcher: "/admin/server-configurator/simulate", method: "POST", middlewares: [validateAndTransformBody(SimulateConfigurationSchema)] },
]
