import { mergeApplicability } from "../../workflows/server-configurator/component-packs/shared/helpers"

const hpeGen10Target = {
  brands: ["HPE"],
  families: ["ProLiant DL360"],
  generations: ["Gen10"],
  server_model_slugs: [
    "hpe-proliant-dl360-gen10-8sff",
    "hpe-proliant-dl360-gen10-8sff-front-drive-option",
    "hpe-proliant-dl360-gen10-10sff-nvme-premium",
    "hpe-proliant-dl360-gen10-4lff",
  ],
}

function slug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")
}

async function upsertPack(service: any, input: any) {
  const [current] = await service.listComponentPacks({ slug: input.slug })
  if (current) return service.updateComponentPacks({ id: current.id, ...input })
  return service.createComponentPacks(input)
}

async function syncItems(service: any, pack: any, components: any[]) {
  const existing = await service.listComponentPackItems({ component_pack_id: pack.id }, { take: 10000 })
  const existingIds = new Set(existing.map((item: any) => item.component_id))
  let added = 0
  for (const component of components) {
    if (existingIds.has(component.id)) continue
    await service.createComponentPackItems({
      component_pack_id: pack.id,
      component_id: component.id,
      sort_order: added + 100,
      enabled: true,
      note: null,
    })
    added += 1
  }
  return { added, total: existing.length + added }
}

function hpeGen10Specs(component: any, pack: any) {
  const specs = component.specs_json || {}
  const current = specs.applicability || {}
  const next = mergeApplicability(component, pack, {
    target_scope: "generation",
    target_values: ["Gen10"],
    mode: "merge",
  })
  const added_values: Record<string, string[]> = {}
  Object.entries(hpeGen10Target).forEach(([key, values]) => {
    const oldValues = Array.isArray(current[key]) ? current[key].map(String) : []
    const merged = Array.from(new Set([...oldValues, ...values]))
    next.applicability[key] = merged
    added_values[key] = merged.filter((value) => !oldValues.includes(value))
  })
  next.pack_applications[pack.id] = {
    ...next.pack_applications[pack.id],
    target_scope: "hpe_gen10_template",
    target_values: hpeGen10Target.server_model_slugs,
    added_values,
  }
  return next
}

export async function createCpuPacks(service: any, cpus: any[]) {
  const first = cpus.filter((item) => item.specs_json?.xeon_scalable_generation === "1st")
  const second = cpus.filter((item) => item.specs_json?.xeon_scalable_generation === "2nd")
  const packInputs = [
    { name: "Intel Xeon Scalable 1st Gen", components: first, generation_scope: ["1st"] },
    { name: "Intel Xeon Scalable 2nd Gen", components: second, generation_scope: ["2nd"] },
    {
      name: "Intel Xeon Scalable 1st/2nd Gen for HPE Gen10",
      components: [...first, ...second],
      brand_scope: ["HPE"],
      family_scope: ["ProLiant DL360"],
      generation_scope: ["Gen10"],
    },
  ]
  const packs: any[] = []
  for (const row of packInputs) {
    const pack = await upsertPack(service, {
      name: row.name,
      slug: slug(row.name),
      description: "CPU component pack generated by Intel Xeon Scalable import.",
      component_type: "cpu",
      brand_scope: row.brand_scope || [],
      family_scope: row.family_scope || [],
      generation_scope: row.generation_scope || [],
      chassis_scope: [],
      tags_json: ["intel", "xeon-scalable", "cpu"],
      applicability_template_json: {},
      enabled: true,
      source_doc_reference: "Intel Product Specifications / curated fallback draft",
    })
    const items = await syncItems(service, pack, row.components)
    packs.push({ pack, items })
    if (row.name.includes("HPE Gen10")) {
      for (const component of row.components) {
        await service.updateComponents({
          id: component.id,
          specs_json: hpeGen10Specs(component, pack),
        })
      }
    }
  }
  return packs
}
