"use client"

import type { ComponentOption, ServerModel } from "@lib/server-configurator/data"
import { AlertTriangle, CheckCircle, Settings2 } from "lucide-react"

export type CompatibilityValidation = { valid: boolean; errors: string[]; warnings: string[]; effective_specs?: Record<string, unknown>; total_price?: number }

export function ConfiguratorSummaryPanel({ model, pending, selectedItems, validation, valid, message, onValidate, onAddToCart, onRequestQuote }: { model: ServerModel; pending: boolean; selectedItems: Array<{ option: ComponentOption; quantity: number }>; validation: CompatibilityValidation | null; valid: boolean; message?: string; onValidate: () => void; onAddToCart: () => void; onRequestQuote: () => void }) {
  return <aside className="server-summary-panel"><div className="server-summary-head"><Settings2 size={22} /><div><h2>Сводка</h2><p>{valid ? "Совместимость подтверждена" : "Нужна проверка"}</p></div>{valid ? <CheckCircle size={18} /> : <AlertTriangle size={18} />}</div><div className="server-summary-line base"><small>Платформа</small><span>{model.public_name}</span></div>{selectedItems.map((item) => <div className="server-summary-line" key={item.option.id}><small>{item.option.type}</small><span>{item.quantity} × {item.option.short_name}</span></div>)}{!selectedItems.length ? <p className="collection-note">Дополнительные компоненты не выбраны.</p> : null}{validation?.errors.length ? <div className="server-summary-messages error">{validation.errors.map((message) => <p key={message}>{message}</p>)}</div> : null}{validation?.warnings.length ? <div className="server-summary-messages warning">{validation.warnings.map((message) => <p key={message}>{message}</p>)}</div> : null}{message ? <p role="status">{message}</p> : null}<p className="summary-commerce-note">Цена и наличие повторно вычисляются Medusa перед действием.</p><button className="server-primary wide" type="button" disabled={pending} onClick={onValidate}>{pending ? "Проверяем…" : "Проверить совместимость"}</button>{valid ? <><button className="server-primary wide" type="button" disabled={pending} onClick={onAddToCart}>Добавить в корзину</button><button className="server-secondary wide" type="button" disabled={pending} onClick={onRequestQuote}>Запросить КП</button></> : null}</aside>
}
