import { DraftXeonCpu } from "./types"

export const intelXeonScalable1stDraft: DraftXeonCpu[] = [
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Bronze", processor_number: "3104", cores: 6, threads: 6, base_frequency_ghz: 1.7, cache_mb: 8.25, tdp_w: 85, max_memory_speed_mhz: 2133, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Bronze", processor_number: "3106", cores: 8, threads: 8, base_frequency_ghz: 1.7, cache_mb: 11, tdp_w: 85, max_memory_speed_mhz: 2133, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Silver", processor_number: "4110", cores: 8, threads: 16, base_frequency_ghz: 2.1, max_turbo_frequency_ghz: 3, cache_mb: 11, tdp_w: 85, max_memory_speed_mhz: 2400, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Silver", processor_number: "4114", cores: 10, threads: 20, base_frequency_ghz: 2.2, max_turbo_frequency_ghz: 3, cache_mb: 13.75, tdp_w: 85, max_memory_speed_mhz: 2400, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Silver", processor_number: "4116", cores: 12, threads: 24, base_frequency_ghz: 2.1, max_turbo_frequency_ghz: 3, cache_mb: 16.5, tdp_w: 85, max_memory_speed_mhz: 2400, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "5118", cores: 12, threads: 24, base_frequency_ghz: 2.3, max_turbo_frequency_ghz: 3.2, cache_mb: 16.5, tdp_w: 105, max_memory_speed_mhz: 2400, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "5120", cores: 14, threads: 28, base_frequency_ghz: 2.2, max_turbo_frequency_ghz: 3.2, cache_mb: 19.25, tdp_w: 105, max_memory_speed_mhz: 2400, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "5122", cores: 4, threads: 8, base_frequency_ghz: 3.6, max_turbo_frequency_ghz: 3.7, cache_mb: 16.5, tdp_w: 105, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6126", cores: 12, threads: 24, base_frequency_ghz: 2.6, max_turbo_frequency_ghz: 3.7, cache_mb: 19.25, tdp_w: 125, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6130", cores: 16, threads: 32, base_frequency_ghz: 2.1, max_turbo_frequency_ghz: 3.7, cache_mb: 22, tdp_w: 125, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6132", cores: 14, threads: 28, base_frequency_ghz: 2.6, max_turbo_frequency_ghz: 3.7, cache_mb: 19.25, tdp_w: 140, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6134", cores: 8, threads: 16, base_frequency_ghz: 3.2, max_turbo_frequency_ghz: 3.7, cache_mb: 24.75, tdp_w: 130, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6136", cores: 12, threads: 24, base_frequency_ghz: 3, max_turbo_frequency_ghz: 3.7, cache_mb: 24.75, tdp_w: 150, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6138", cores: 20, threads: 40, base_frequency_ghz: 2, max_turbo_frequency_ghz: 3.7, cache_mb: 27.5, tdp_w: 125, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6140", cores: 18, threads: 36, base_frequency_ghz: 2.3, max_turbo_frequency_ghz: 3.7, cache_mb: 24.75, tdp_w: 140, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6142", cores: 16, threads: 32, base_frequency_ghz: 2.6, max_turbo_frequency_ghz: 3.7, cache_mb: 22, tdp_w: 150, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6148", cores: 20, threads: 40, base_frequency_ghz: 2.4, max_turbo_frequency_ghz: 3.7, cache_mb: 27.5, tdp_w: 150, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Gold", processor_number: "6152", cores: 22, threads: 44, base_frequency_ghz: 2.1, max_turbo_frequency_ghz: 3.7, cache_mb: 30.25, tdp_w: 140, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Platinum", processor_number: "8160", cores: 24, threads: 48, base_frequency_ghz: 2.1, max_turbo_frequency_ghz: 3.7, cache_mb: 33, tdp_w: 150, max_memory_speed_mhz: 2666, launch_date: "Q3'17" },
  { generation: "1st", platform_generation: "Skylake-SP", code_name: "Skylake", tier: "Platinum", processor_number: "8180", cores: 28, threads: 56, base_frequency_ghz: 2.5, max_turbo_frequency_ghz: 3.8, cache_mb: 38.5, tdp_w: 205, max_memory_speed_mhz: 2666, launch_date: "Q3'17", special_sku_notes: ["High TDP; verify server cooling and BIOS support."] },
]
