import { model } from "@medusajs/framework/utils"

const Configuration = model.define("configuration", {
  id: model.id().primaryKey(),
  server_model_id: model.text(),
  medusa_cart_id: model.text().nullable(),
  medusa_line_item_id: model.text().nullable(),
  medusa_customer_id: model.text().nullable(),
  medusa_order_id: model.text().nullable(),
  status: model.enum([
    "draft",
    "valid",
    "invalid",
    "in_cart",
    "quote_requested",
    "quoted",
    "ordered",
    "expired",
    "archived",
  ]).default("draft"),
  price_mode: model.enum(["calculated", "request_quote"]).default("request_quote"),
  currency_code: model.text().nullable(),
  total_price: model.bigNumber().default(0),
  priced_at: model.dateTime().nullable(),
  price_expires_at: model.dateTime().nullable(),
  ready_configuration_id: model.text().nullable(),
  ready_configuration_version: model.number().nullable(),
  ready_snapshot_hash: model.text().nullable(),
  storage_option_id: model.text().nullable(),
  explicit_none_json: model.json().nullable(),
  effective_specs_json: model.json().nullable(),
  warnings_json: model.json().nullable(),
  errors_json: model.json().nullable(),
  snapshot_json: model.json().nullable(),
  hash: model.text().nullable(),
  order_snapshot_json: model.json().nullable(),
  order_snapshot_hash: model.text().nullable(),
  ordered_at: model.dateTime().nullable(),
})

export default Configuration
