import { model } from "@medusajs/framework/utils"

const ServerModel = model.define("server_model", {
  id: model.id().primaryKey(),
  medusa_product_id: model.text().nullable(),
  medusa_variant_id: model.text().nullable(),
  technology_platform_id: model.text().nullable(),
  vendor_generation_template_id: model.text().nullable(),
  server_family_id: model.text().nullable(),
  capability_profile_id: model.text().nullable(),
  brand: model.text(),
  family: model.text(),
  generation: model.text(),
  model: model.text(),
  public_name: model.text(),
  slug: model.text(),
  form_factor: model.text(),
  chassis_type: model.text(),
  drive_bays_front: model.number(),
  drive_bays_rear: model.number().default(0),
  drive_form_factor: model.text(),
  supported_drive_interfaces: model.array().nullable(),
  front_option_type: model.text().nullable(),
  backplane_type: model.text(),
  cpu_socket: model.text(),
  max_cpu: model.number(),
  ram_slots_total: model.number(),
  ram_slots_per_cpu: model.number(),
  max_ram_capacity: model.text(),
  supported_ram_types: model.array().nullable(),
  supported_ram_speeds: model.array().nullable(),
  psu_type: model.text(),
  cooling_profile: model.text(),
  seo_title: model.text(),
  seo_description: model.text(),
  source_doc_reference: model.text(),
  schema_version: model.number().default(1),
  enabled: model.boolean().default(true),
})

export default ServerModel
